name = "Minecraftify Your Items!"
description = "Why let all that junk lay around your base when you can let it float!"
author = "LukaS"
version = "1.1.2"
forumthread = "/profile/365042-lukas/"
icon_atlas = "icon.xml"
icon = "icon.tex"
client_only_mod = true
all_clients_require_mod = false
dst_compatible = true
reign_of_giants_compatible = false
dont_starve_compatible = false
priority = 0
api_version = 10